### ISSUE TITLE
Download Raw Data for Supporting Facilities

### ISSUE THREAD

**Issue by SamanthaBurn** [SamanthaBurn/nhs-data-pipeline#1]
**Objective**:
Modify the Python script to download raw files from [Supporting Facilities Data](https://www.england.nhs.uk/statistics/statistical-work-areas/cancelled-elective-operations/supporting-facilities-data/) and aggregate across all years.

**Tasks**:
- [x] Clone the repo to your local machine
- [x] Generate and run a Python configuration script that makes sure all the necessary packages are installed. (Do you know how to use virtual environments? If yes, that would be even better)
- [x] Run the `scripts/extract-supporting-facilities.py` script. Check that all the files are downloaded to your 'rawdata/supporting-facilties' folder
- [x] Check if there are any files that weren't downloaded. Investigate the source of the problem and document in this issue! (I just ran this on my machine and it seems like a couple of the links were broken. Can you find these files? If yes, please document! If no, then just interpolate for the missing quarter and document
- [x] Generate a Python script that (i) loops through all the files and extracts (i) organisation code, (ii) number of operating theatres (iii) number of daycase theatres, (iv) year and (v) quarter and saves to 'data/supporting-facilities.csv'. Note that the earlier years have separate tabs within an excel file containing the quarters, so you'll have to write a different routine for them
- [x] In the script check that there are no years/quarters missing
- [x] Commit the changes and push to the main repo. Check that the raw data hasn't been pushed!

**Deliverable**:
- [x] A dataset (`supporting_facilities.csv`) that compiles all fields for all years.
- [ ] A simple codebook (in csv format) just listing the field names, a description, and the datafile they appear in
